import { type Star } from "./starsApi";
import starIllustration from "../../images/stars_illustration.jpg";

export const STARS_MOCK: Star[] = [
  {
    id: 1,
    name: "Сириус",
    spectral_class: "A1V",
    constellation: "Большой Пёс",
    epoch: "J2000",
    ra: "06h 45m 08.9s",
    declension: "-16° 42′ 58″",
    magnitude: "-1.46",
    alt_names: "α CMa, Dog Star",
    image_url: starIllustration,
  },
  {
    id: 2,
    name: "Бетельгейзе",
    spectral_class: "M2Iab",
    constellation: "Орион",
    epoch: "J2000",
    ra: "05h 55m 10.3s",
    declension: "+07° 24′ 25″",
    magnitude: "0.42",
    alt_names: "α Ori",
    image_url: "",
  },
  {
    id: 3,
    name: "Ригель",
    spectral_class: "B8Ia",
    constellation: "Орион",
    epoch: "J2000",
    ra: "05h 14m 32.3s",
    declension: "−08° 12′ 06″",
    magnitude: "0.18",
    alt_names: "β Ori",
    image_url: "",
  },
  {
    id: 4,
    name: "Процион",
    spectral_class: "F5IV-V",
    constellation: "Малый Пёс",
    epoch: "J2000",
    ra: "07h 39m 18.1s",
    declension: "+05° 13′ 30″",
    magnitude: "0.34",
    alt_names: "α CMi",
    image_url: "",
  },
  {
    id: 5,
    name: "Вега",
    spectral_class: "A0V",
    constellation: "Лира",
    epoch: "J2000",
    ra: "18h 36m 56.3s",
    declension: "+38° 47′ 01″",
    magnitude: "0.03",
    alt_names: "α Lyr",
    image_url: "",
  },
  {
    id: 6,
    name: "Альтаир",
    spectral_class: "A7V",
    constellation: "Орел",
    epoch: "J2000",
    ra: "19h 50m 47.0s",
    declension: "+08° 52′ 06″",
    magnitude: "0.77",
    alt_names: "α Aql",
    image_url: "",
  },
  {
    id: 7,
    name: "Антарес",
    spectral_class: "M1.5Iab-b",
    constellation: "Скорпион",
    epoch: "J2000",
    ra: "16h 29m 24.4s",
    declension: "−26° 25′ 55″",
    magnitude: "1.09",
    alt_names: "α Sco",
    image_url: "",
  },
  {
    id: 8,
    name: "Полярная звезда",
    spectral_class: "F7Ib",
    constellation: "Малая Медведица",
    epoch: "J2000",
    ra: "02h 31m 49.1s",
    declension: "+89° 15′ 51″",
    magnitude: "1.98",
    alt_names: "α UMi, Polaris",
    image_url: "",
  },
];
